#!/usr/bin/env python3
"""Generate a sidecar Click CLI (daas_cli.py) from a descriptor.

Wraps only functions with has_existing_cli == false. Imports the original
package via importlib; does NOT modify the original project. Each command takes
the function's parameters as --options and prints the result as JSON records.

Usage:
    python gen_cli.py <descriptor.json> --import-root <pkg> [--out daas_cli.py]
"""
from __future__ import annotations

import argparse
import json
import textwrap
from pathlib import Path


def _py_type(annotation: str, default) -> str:
    """Map a Python annotation/default to a Click type name."""
    a = (annotation or "").strip()
    if a in ("int", "Integer"):
        return "int"
    if a in ("float", "Float"):
        return "float"
    if a in ("bool", "Boolean"):
        return "bool"
    if default in ("True", "False"):
        return "bool"
    if default not in (None, "None"):
        try:
            int(str(default))  # noqa: F841
            return "int"
        except ValueError:
            pass
        try:
            float(str(default))  # noqa: F841
            return "float"
        except ValueError:
            pass
    return "str"


def _cmd_for(func: dict, import_root: str) -> str:
    name = func["name"]
    fn_attr = name.split(".")[-1]
    params = [p for p in func.get("parameters", []) if p.get("name") not in ("self", "cls")]
    opts: list[str] = []
    call_args: list[str] = []
    for p in params:
        pname = p["name"]
        ptype = _py_type(p.get("annotation", ""), p.get("default"))
        type_clause = f", type={ptype}" if ptype != "str" else ""
        dv = p.get("default")
        required = p.get("required") and (dv in (None, "None"))
        if required:
            req_clause = ", required=True"
            default_clause = ""
        else:
            req_clause = ""
            # repr() yields a valid Python literal for str/int/float/bool
            default_clause = f", default={repr(dv)}" if dv is not None else ", default=None"
        help_text = (p.get("description") or "").replace('"', "'")[:80]
        flag = pname.replace("_", "-")
        opts.append(
            f'@click.option("--{flag}", "{pname}"{type_clause}{req_clause}{default_clause}, '
            f'help="{help_text}")'
        )
        call_args.append(f"{pname}={pname}")

    opts_block = "\n".join(opts) if opts else "    pass"
    call = ", ".join(call_args)
    doc = (func.get("description") or func.get("label") or name).replace('"', "'")[:200]
    cmd_name = name.replace("_", "-")
    py_name = name.replace(".", "_").replace("-", "_") + "_cmd"
    param_list = ", ".join(p["name"] for p in params)
    return textwrap.dedent(f'''
@cli.command("{cmd_name}", help="{doc}")
{opts_block}
def {py_name}({param_list}):
    """{doc}"""
    import importlib
    mod = importlib.import_module("{import_root}")
    fn = getattr(mod, "{fn_attr}")
    result = fn({call})
    _emit(result)
''').lstrip()


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("descriptor")
    ap.add_argument("--import-root", required=True,
                    help="dotted package root to import, e.g. akshare or tiny_econ.api")
    ap.add_argument("--out", default="daas_cli.py")
    args = ap.parse_args()

    desc = json.loads(Path(args.descriptor).read_text(encoding="utf-8"))
    funcs = [f for f in desc.get("daas_functions", []) if not f.get("has_existing_cli", False)]
    cmds = "\n\n".join(_cmd_for(f, args.import_root) for f in funcs)

    src = desc.get("source", {})
    src_name = src.get("name", "<source>")
    src_label = src.get("label", src_name)

    header = textwrap.dedent(f'''\
#!/usr/bin/env python3
"""Sidecar CLI for {src_name} - generated by fd-daas-datasource-builder.
Imports the original package ({args.import_root}); does not modify it.
Each command prints JSON records. Install deps with: uv run --with <deps> python daas_cli.py ..."""
import json

import click

try:
    import pandas as pd
except ImportError:
    pd = None


def _emit(result):
    if pd is not None and isinstance(result, pd.DataFrame):
        print(result.to_json(orient="records", force_ascii=False, date_format="iso"))
    elif isinstance(result, (list, tuple)):
        print(json.dumps(list(result), ensure_ascii=False, default=str))
    elif isinstance(result, dict):
        print(json.dumps(result, ensure_ascii=False, default=str))
    else:
        print(json.dumps(str(result), ensure_ascii=False))


@click.group()
def cli():
    """{src_label} sidecar CLI (auto-generated)."""
    pass


{cmds}


if __name__ == "__main__":
    cli()
''')
    Path(args.out).write_text(header, encoding="utf-8")
    print(f"wrote {args.out}: {len(funcs)} command(s) "
          f"({len(desc.get('daas_functions', []))} total functions, "
          f"{len(desc.get('daas_functions', [])) - len(funcs)} skipped as already-CLI'd)")


if __name__ == "__main__":
    main()
