#!/usr/bin/env python3
"""Sync resolved YAML config defaults into Markdown files.

Reads default.yaml, save/template.agents.yaml, and save/template.workflows.yaml,
resolves each section's `default` key against its `registry` via get_config.py,
and writes a ``## System Config`` section into CLAUDE.md and agents.md.

Usage:
    python script/update_system_config.py
"""

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent

CONFIG_FILES: list[tuple[Path, str]] = [
    (PROJECT_ROOT / "default.yaml", "default.yaml"),
    (PROJECT_ROOT / "save" / "template.agents.yaml", "template.agents.yaml"),
    (PROJECT_ROOT / "save" / "template.workflows.yaml", "template.workflows.yaml"),
]

TARGET_FILES: list[Path] = [
    PROJECT_ROOT / "CLAUDE.md",
    PROJECT_ROOT / "agents.md",
]

# Matches an existing ## System Config section through to the next ## heading or EOF
SECTION_PATTERN = re.compile(r"^## System Config$.*?(?=^## |\Z)", re.MULTILINE | re.DOTALL)


def run_get_config(file_path: Path) -> Optional[dict]:
    """Invoke get_config.py --json --file <path>, return the parsed dict.

    Returns None if the config file is missing, the subprocess fails, or
    no sections were resolved.
    """
    get_config_script = Path(__file__).resolve().parent / "get_config.py"

    if not file_path.exists():
        print(
            f"Warning: config file not found, skipping: {file_path}",
            file=sys.stderr,
        )
        return None

    try:
        result = subprocess.run(
            [sys.executable, str(get_config_script), "--json", "--file", str(file_path)],
            capture_output=True,
            text=True,
            timeout=30,
        )
    except subprocess.TimeoutExpired:
        print(
            f"Warning: get_config.py timed out for {file_path}",
            file=sys.stderr,
        )
        return None

    if result.returncode != 0:
        print(
            f"Warning: get_config.py failed for {file_path}: {result.stderr.strip()}",
            file=sys.stderr,
        )
        return None

    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError as e:
        print(
            f"Warning: failed to parse JSON from get_config.py for {file_path}: {e}",
            file=sys.stderr,
        )
        return None

    if not data:
        print(
            f"Warning: no resolved sections in {file_path}",
            file=sys.stderr,
        )
        return None

    return data


def build_system_config_section(resolved: dict) -> str:
    """Build the ``## System Config`` markdown section from resolved configs."""
    lines: list[str] = [
        "## System Config",
        "",
        "> Auto-generated by `script/update_system_config.py`. Do not edit manually.",
        "",
    ]

    for section_name in sorted(resolved.keys()):
        entry = resolved[section_name]
        default_id = entry["default"]
        config = entry["config"]

        lines.append(f"### {section_name}")
        lines.append("")
        lines.append(f"- **Default**: `{default_id}`")
        lines.append("")

        yaml_str = yaml.dump(
            config,
            default_flow_style=False,
            indent=2,
            allow_unicode=True,
            sort_keys=False,
        )
        lines.append("```yaml")
        lines.append(yaml_str.rstrip())
        lines.append("```")
        lines.append("")

    return "\n".join(lines)


def update_or_create_file(file_path: Path, markdown_section: str) -> None:
    """Replace or append the ``## System Config`` section in a markdown file."""
    if file_path.exists():
        content = file_path.read_text(encoding="utf-8")

        if SECTION_PATTERN.search(content):
            new_content = SECTION_PATTERN.sub(markdown_section, content)
        else:
            if not content.endswith("\n"):
                content += "\n"
            new_content = content + "\n" + markdown_section + "\n"
    else:
        new_content = markdown_section + "\n"

    file_path.write_text(new_content, encoding="utf-8")


def main() -> int:
    resolved_all: dict = {}

    for file_path, label in CONFIG_FILES:
        result = run_get_config(file_path)
        if result is not None:
            resolved_all.update(result)

    if not resolved_all:
        print(
            "Warning: no resolved configs found. Nothing to do.",
            file=sys.stderr,
        )
        return 0

    try:
        markdown_section = build_system_config_section(resolved_all)
    except Exception as e:
        print(f"Error: failed to generate markdown: {e}", file=sys.stderr)
        return 1

    for target_file in TARGET_FILES:
        if target_file.name == "CLAUDE.md" and not target_file.exists():
            print(
                f"Error: CLAUDE.md not found at {target_file}",
                file=sys.stderr,
            )
            return 1

        try:
            update_or_create_file(target_file, markdown_section)
            print(f"Updated: {target_file}")
        except OSError as e:
            print(
                f"Error: failed to write {target_file}: {e}",
                file=sys.stderr,
            )
            return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
